### ISSUE TITLE
DAST Tool - Layout for Dashboard Tabs

### ISSUE THREAD

**Issue by juhiechandra** [Risk-Assessment-Framework/RAF-DAST-Scanner#9]
**Description:**
The current dashboard for the DAST tool under the OWASP Risk Assessment Framework lacks a consistent layout for tabs like Tools, Resources, Documentation, and Support. To make the dashboard more user-friendly, we need to decide on a layout for these tabs and integrate them into the dashboard.

**Tasks:**

- [x] Discuss and finalize the layout for the Tools, Resources, Documentation, and Support tabs.
- [ ] Update the code to integrate the new layout for the tabs.
- [ ] Test the updated dashboard for any bugs or errors.
- [ ] Deploy the updated dashboard to the production environment.

Additional Information
Dashboard URL: [View here](https://raf-dast-scanner.vercel.app/dashboard)
DAST Tool repository: [View code here](https://github.com/Risk-Assessment-Framework/RAF-DAST-Scanner/tree/main/Frontend/src/pages)

**Comment by juhiechandra** [comment]
@adeyosemanputra I request you to assign me this issue. I will finish this.

**Comment by juhiechandra** [comment]
Submitted designs for review as of 29th March 2023

**Comment by juhiechandra** [comment]
**Starting with Navbar:**

**When an unauthorized user enters:**
<img width="879" alt="Screenshot 2023-04-01 at 7 13 51 PM" src="https://user-images.githubusercontent.com/75068056/229292695-4ce2030d-2bb9-4971-be0d-7878e3528e87.png">

**When an authorized user enters:**
<img width="1021" alt="Screenshot 2023-04-01 at 7 14 39 PM" src="https://user-images.githubusercontent.com/75068056/229292744-fe2c3502-4400-4c4d-a9fa-5e1c2c375a61.png">
